[server]
# Адрес для прослушивания (0.0.0.0 - слушает все сетевые интерфейсы; Можно указать 127.0.0.1 для только локальных подключений)
host = 0.0.0.0
# Порт для gRPC
port = 5080

[client]
# Адрес сервера для подключения
server_host = localhost
# Порт
server_port = 5080